project:
  type: website
  output-dir: docs

website:
  title: "nf-core workflows series"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: setup.html
        text: "Setup"
      - text: "Session 1"
        menu:
        - text: "Lesson template"
          href: notebooks/0.0_template.html
      - text: "Session 2"
        menu:
        - text: "Sesson 2 kick-off"
          href: notebooks/2.0_part2.html
        - text: "CLI flags"
          href: notebooks/2.1_flags.html
        - text: "Params file"
          href: notebooks/2.2_paramsfile.html
        - text: "Custom configs"
          href: notebooks/2.3_config.html
        - text: "Params & configs"
          href: notebooks/2.4_paramsconfig.html
        - text: "Custom module"
          href: notebooks/2.5_custommodule.html
  body-footer: "All materials copyright Sydney Informatics Hub, University of Sydney"
          
format:
  html:
    theme: simplex
    css: [lesson.css, bootstrap-icons.css]
    toc: true
    code-overflow: wrap
    highlight-style: github




