project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Sydney Informatics Hub training"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: setup.html
        text: "Setup"
      - href: notebooks/0.0_welcome.html
        text: "Lesson plan"      
      - text: "Session 1"
        menu:
        - text: "1.0 Session 1 kick-off"
          href: notebooks/1.0_intro.html
        - text: "1.1 Introduction to Nextflow"
          href: notebooks/1.1_nextflow.html
        - text: "1.2 Introduction to nf-core"
          href: notebooks/1.2_nfcore.html 
        - text: "1.3 Configuring nf-core workflows"
          href: notebooks/1.3_configure.html
        - text: "1.4 Commands for users"
          href: notebooks/1.4_users.html
      - text: "Session 2"
        menu:
        - text: "2.0 Session 2 kick-off"
          href: notebooks/2.0_intro.html
        - text: "2.1 Design a run command"
          href: notebooks/2.1_design.html
        - text: "2.2 Use a parameters file"
          href: notebooks/2.2_params.html
        - text: "2.3 Configure resources"
          href: notebooks/2.3_configEnv.html
        - text: "2.4 Apply multiple configurations"
          href: notebooks/2.4_multiConfig.html
        - text: "2.5 Apply external arguments"
          href: notebooks/2.5_extArgs.html
      - text: "Tips & Tricks"
        href: tips_tricks.html
  body-footer: "All materials copyright Sydney Informatics Hub, University of Sydney"

          
format:
  html:
    theme: 
      light: flatly
    css: styles.scss
    toc: true
    code-overflow: scroll
    highlight-style: github
    page-layout: full
