project:
  type: website
  output-dir: docs

website:
  title: "nf-core workflows series"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: setup.html
        text: "Setup"
      - text: "Session 1"
        menu:
        - text: "Lesson template"
          href: notebooks/0.0_template.html
      - text: "Session 2"
        menu:
        - text: "Sesson 2 kick-off"
          href: notebooks/2.0_intro.html
        - text: "Run command design"
          href: notebooks/2.1_design.html
        - text: "Using a parameters file"
          href: notebooks/2.2_params.html
        - text: "Configuring a workflow run"
          href: notebooks/2.3_configEnv.html
        - text: "Using multiple configurations"
          href: notebooks/2.4_multiConfig.html
        - text: "Using external arguments"
          href: notebooks/2.5_extArgs.html
        - text: "Troubleshooting issues"
          href: notebooks/2.6_troubleshoot.html
  body-footer: "All materials copyright Sydney Informatics Hub, University of Sydney"
          
format:
  html:
    theme: simplex
    css: [lesson.css, bootstrap-icons.css]
    toc: true
    code-overflow: wrap
    highlight-style: github




