---
title: "Customising nf-core workflows"
output:
  html_document:
    toc: false
    toc_float: false
---


**This course is currently under development**


## Trainers

* Cali Willet 
* Georgie Samaha

## Course pre-requisites and setup requirements



## Venue, online via Zoom
Participants will be provided with a Zoom link. Trainers will be broadcasting from Sydney.

#### Zoom etiquette and how we interact

* Do not use Zoom chat. Instead use Slack channel for help and discussion 
* 

## Code of Conduct
We expect all attendees of our training to follow our code of conduct, including bullying, harassment and discrimination prevention policies.

In order to foster a positive and professional learning environment we encourage the following kinds of behaviours at all our events and on our platforms:

* Use welcoming and inclusive language
* Be respectful of different viewpoints and experiences
* Gracefully accept constructive criticism
* Focus on what is best for the community
* Show courtesy and respect towards other community members

Our full CoC, with incident reporting guidelines, is available [here]https://sydney-informatics-hub.github.io/codeofconduct/).

## General session timings

* ...


## Setup Instructions

Please complete the [Setup Instructions](./setup.html) **before the course**.

If you have any trouble, please get in contact with us ASAP.
