---
title: "**2.0. Introduction to session 2**"
output:
  html_document:
    toc: false
    toc_float: false
from: markdown+emoji
---

This session builds on fundamental concepts learned in [Session 1](1.0_intro.md) and provides you with hands-on experience in nf-core workflow customisation. Throughout the session we will be working with a case study and the nf-core/rnaseq pipeline. We will explore the pipeline source code and apply customisations using a parameter file and custom configuration files. You will create these files, use the nf-core tools utility, run Nextflow commands and some custom **bash** code to efficiently extract information from the source code :nerd_face:. 

::: callout-note
### Applying what you learn here to other nf-core workflows
While all activities in this session will be performed using the nf-core/rnaseq workflow, all customisation scenarios we explore are applicable to other nf-core workflows and do not require an understanding of RNAseq data processing. 
:::

### **2.0.1. Session 2 lesson plan**

Each lesson in this session will build on the previous lessons, so you can gain a deeper understanding of the customisation techniques and the impact they have on the workflow and your results. There are many different ways to customise a pipeline and we will learn to:

* Session 2.1: Build a run command for the nf-core/rnaseq pipeline using required and optional parameters   
* Session 2.2: Troubleshoot a pipeline warning message and apply a params file to track our parameters 
* Session 2.3: Configure compute resources for the workflow using custom and institutional configuration files 
* Session 2.4: Apply multiple configurations to the workflow for the same run
* Session 2.5: Supply external arguments to a process that are not preset as pipeline parameters 

### **2.0.2. Log back in to your instance**

Follow [set up instructions](../setup.html) to log back into your instance. 

### **2.0.3. Create a new work directory**

Create a new directory for all session 2 activities and move into it: 

```default
mkdir ~/session2 && cd $_
```
