name: Generate images for docs
on:
  workflow_dispatch:
jobs:
  rich_codex:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1

      - name: Install nf-core/tools
        run: pip install nf-core

      - name: Generate terminal images with rich-codex
        # Change back to @v1 when v1.2.7 is released
        uses: ewels/rich-codex@main
        env:
          COLUMNS: 100
          HIDE_PROGRESS: 'true'
          NXF_ANSI_LOG: false
        with:
          commit_changes: 'true'
          terminal_width: 100
          skip_git_checks: 'true'
